### ISSUE TITLE
Home page content

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-frontend#1]
Home page content needs to be improved. Noah mentioned that the word "hackathon" appears nowhere on the current homepage (https://revolutionuc.com). The home page should contain more information, talk to marketing about this.

**Comment by jonathanGB** [comment]
yeah Home page content is definitely an issue, @domfarolino should look into it ASAP

**Comment by noahbass** [comment]
As of 156416c the homepage content has been refined (and includes the word 'hackathon'!).

Closing.
🎉 🎉
