### ISSUE TITLE
Lighthouse report (DESKTOP)

### ISSUE THREAD

**Issue by devagrawal09** [RevolutionUC/revolutionuc-frontend#121]
Lighthouse gave revolutionuc.com a performance score of 56, and accessibility score of 78.

Need to work on major performance upgrades.

Starting with #3, images are unnecessarily big.

**Comment by WillCPP** [comment]
We can have responsive image sizes with the srcset attribute.  Appropriately sized images can then be loaded in for different screen sizes.
