### ISSUE TITLE
Refine hamburger menu (mobile navigation)

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-frontend#20]
Current nav hamburger (screenshot from an iphone 7):

![image_123986672](https://user-images.githubusercontent.com/3453188/34084315-eb0bb4c8-e34b-11e7-9ce0-d670e8ece19b.JPG)

Possible fix: use an svg or pure css for the hamburger? https://thenounproject.com/term/hamburger-menu/204478/

**Comment by snyderks** [comment]
I would say probably just copy the styles and SVG from old RevUC site

**Comment by noahbass** [comment]
Closed via 865c3032b8cb59245655a4bb95300555a830c568
