### ISSUE TITLE
Change the pic of @isiah-lloyd on the homepage

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-frontend#21]
Sorry @isiah-lloyd, I guess we can't have you featured on the homepage 😒

**Comment by domfarolino** [comment]
Yeah it's a little rough :)

**Comment by kurtlewis** [comment]
It'd also be nice to update the image on the schedule page

**Comment by kurtlewis** [comment]
And something else to think about - it'd be nice to have more imagery featuring women

**Comment by snyderks** [comment]
Resolved with #43.

**Comment by kurtlewis** [comment]
I don't always see these things as they happen, but I really like the changes you made here!
