### ISSUE TITLE
Add WebAppManifest for browser chrome styling on android

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-frontend#23]
A template for this can be found [here](https://github.com/RevolutionUC/revolutionuc-website/blob/master/public/manifest.json) though we'll want to update some of the info and not add stuff for web push.

**Comment by WillCPP** [comment]
Added in 9a642ef0c78f7e1f5af43fd23332f717ea4cf58b, 749e46985a9c127c63ae642bea98e0f0f17780e1, and 760a7ed1e1fd4d6badb7371569c17561f40cf06e
