### ISSUE TITLE
Anyone else have to run `sudo bundle install`?

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-frontend#29]
/cc @isiah-lloyd I find that I have to run `sudo` to install the bundle. I assume this isn't expected?

**Comment by snyderks** [comment]
As a comment, this usually means that either bundle, ruby, or gem is installed in a directory that needs sudo so it can't run it without that.

**Comment by domfarolino** [comment]
Duh. This doesn't happen on my laptop too; closing this
