### ISSUE TITLE
Use a Fetch API pollyfill

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-frontend#36]
Not all browsers support the fetch api, particularly IE11: https://caniuse.com/#feat=fetch

Use a pollyfill for fetch: https://github.com/github/fetch

cc @domfarolino

**Comment by noahbass** [comment]
Also, we need to use a Promise polyfill as IE11 does not support promises 👎 

https://github.com/RevolutionUC/revolutionuc-frontend/blob/76e2bc24491d054f88c7c5ce3dbd71c5b6f873c6/register.html#L247-L252

In addition, IE11 doesn't even support classes: https://github.com/RevolutionUC/revolutionuc-frontend/blob/77d5e368c58064cee4b0a8af7730698d7320d465/js/register.js#L1-L9

With all this in mind, should we just not support IE11? If so, we'll need to tell the user its not supported with a message if they visit the register page on IE11.

@domfarolino @kurtlewis @isiah-lloyd

**Comment by domfarolino** [comment]
I think we should stop supporting IE11. I'm all for a message indicating their browser is not supported if that works with the aforementioned @-mentioned.

If we decide to go with this, we can close this and open a new more-specific issue

**Comment by kurtlewis** [comment]
3% of people use IE11 https://www.w3counter.com/globalstats.php, but I can't imagine many in our demographic.

Buuut I just looked up our google analytics stats and we've had 30 visitors from IE this week alone. I'd rather not drop support, but I don't know enough about this problem to say it's worth supporting it.

**Comment by kurtlewis** [comment]
I especially enjoy this ^ because I'm asking the engineering team to do things without understanding the problem. Sign me up for management! 😆

**Comment by domfarolino** [comment]
If we're still looking to support IE then looks like we'll need some babel step or something to make the JS work. Alternatively I guess we could just port it to ES5 and use the fetch polyfill. Thoughts @isiah-lloyd ?

**Comment by isiah-lloyd** [comment]
I probably could setup Babel as part of our CI so we don't have to worry
about ES5 compatibility.

**Comment by devagrawal09** [comment]
It's been 2 years, can we drop IE11 support now please? I think it should be safe to assume that students will not be using IE at all.

**Comment by devagrawal09** [comment]
I see 1.5% IE users between Dec 19 and March 20. This number will only drop for 21. Closing.

**Comment by devagrawal09** [comment]
Correction - 2.8% users, and 1.6% sessions
