### ISSUE TITLE
Small Design Considerations

### ISSUE THREAD

**Issue by isiah-lloyd** [RevolutionUC/revolutionuc-frontend#5]
- [x] Navbar active style doesn't change
- [x] Navbar background color flashes on load (homepage only) - make the homepage navbar transparent by default to fix this
- [x] MLH banner overlays nav hamburger on mobile
- [x] google analytics snippet in footer
- [x] use `srcset` on photos that can be displayed at 2x
- [x] use svg for the navbar logo (Zach is currently working on the svg version)
- [x] Replace 'Register Now' buttons with 'Be Notified' buttons

- Sponsors
  - [x] Have sponsors span across multiple columns (2?)
  - [x] Use a white background for this page

- FAQ
  - [x] Choose a different photo for FAQ page
  - [x] FAQ table of contents or expandos

- Homepage
  - [x] Make links to previous hackathons prettier (no plain text, perhaps roll over text?)
  - [x] Light blue overlay does not cover entire video (see screenshot below)
  - [x] No padding between photo and video (see screenshot; there was padding on Kyle's screenshot, could just be my browser (Chrome 63, Windows 10))
  - [x] Video extends over the .hero div (see screenshot)
  - [x] Use image instead of video on mobile (never load video if on mobile)
    - Perhaps use a background-image in a media query for mobile, then use js to load in the video on non-mobile
  - [x] Finish homepage content

- Basic seo
  - [x] Add twitter and facebook meta tags to header.html
  - [x] add meta description for each page
  - [x] jekyll/jekyll-sitemap

![image](https://user-images.githubusercontent.com/885544/33862637-ba242cc6-deb1-11e7-8983-2f2c158d158c.png)

**Comment by isiah-lloyd** [comment]
@snyderks You ok to fix the issues on the sponsor page?
@noahbass You good with the FAQ page changes
I'll try at fixing the homepage fixes.
Active link issue was fixed via #6

**Comment by snyderks** [comment]
Yes I'll fix the sponsor page
