### ISSUE TITLE
Add stickermule logo

### ISSUE THREAD

**Issue by kurtlewis** [RevolutionUC/revolutionuc-frontend#53]
We can add them as a partner - not a sponsor. Needs to link here: http://hackp.ac/mlh-stickermule-hackathons

Logo: https://www.stickermule.com/press?utm_source=All%20Hackathon%20Organizers&utm_medium=email.

**Comment by kurtlewis** [comment]
update: i see we don't have a 'partners' section, so we can just add them at the bottom

**Comment by noahbass** [comment]
Closed via 0e464a2c7f511f5ff42b0347b522506313bf2138

**Comment by kurtlewis** [comment]
Thank you!
