### ISSUE TITLE
Dashboard - 2021*

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-frontend#65]
Here are some nice changes it would be to have for next time:

 - UI exposed on the dashboard to take advantage of [sending email verification](https://github.com/RevolutionUC/revolutionuc-website/blob/master/lib/api/email.js#L28) emails via the API.
 - Each email-sending API endpoint returns the number of registrants affected by the operation. It would be nice to have UI in the dashboard for each operation, that shows the result of the API call on the frontend so we know whether the operation has succeeded/failed. Since I haven't spent much time on the dashboard UI, I'm doing this a little more manually now with DevTools, but for other organizers it would be nice to have this

...I'll keep updating this as I think of more; the main point is that we've got a front- and back-end that can work well for years to come, so some of the operational components (like dashboard) can improve over time.

**Comment by devagrawal09** [comment]
Moved to https://github.com/RevolutionUC/revolutionuc-admin/issues/9
