### ISSUE TITLE
Menu dissappears sitting at the top of the page

### ISSUE THREAD

**Issue by Samwisebuze** [RevolutionUC/revolutionuc-frontend#72]
# Image of the issue

![image](https://user-images.githubusercontent.com/16690404/47523882-25ab1400-d867-11e8-858c-3ef4fbf60b14.png)

> I am at the top of the page (cannot scroll up) and there is no menu

## Reproduce

Open the Sponsor page and scroll down a tiny bit then immediately back up. Scrolling down triggers the menu and makes it recceed. If you scroll back to the top before that animation finishes, the menu doesn't reappear.

**Comment by WillCPP** [comment]
Fixed in commit a80e6cae24384774430c7808398777a078d0cba0.

https://github.com/RevolutionUC/revolutionuc-frontend/commit/a80e6cae24384774430c7808398777a078d0cba0
