### ISSUE TITLE
Shrunken sponsor images

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-frontend#77]
Occasionally when I visit the sponsors page the webp images look like they’ve been shrunken.

Browser: Chrome 70.0.3538.110
OS: 10.14.1

<img width="900" alt="screen shot 2018-12-08 at 1 29 29 pm" src="https://user-images.githubusercontent.com/3453188/49689340-da368780-faed-11e8-9f8b-5dd92e139d0c.png">

**Comment by WillCPP** [comment]
Fixed in e22937b3fd5f562c212f8f0071b19a30ab422151
