### ISSUE TITLE
Gender field update

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-frontend#79]
Gender field options on registration should be updated to:

- `Male`
- `Female`
- `Non-Binary / Third Gender`
- `Other`
- `Prefer Not to Answer`

**Comment by isiah-lloyd** [comment]
Requires validation changes on the back-end

**Comment by isiah-lloyd** [comment]
Updated acceptable gender values =  ['Male', 'Female', 'NonBinary', 'Other', 'PreferNot'];

**Comment by WillCPP** [comment]
Fixed by e8ed318f9edf33607d4a7b82029e6a2b2d5bee68
