### ISSUE TITLE
Set noindex on hidden pages

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-frontend#80]
There are a handful of pages (attendance-confirmed.html, attendance-denied.html, etc.) that should be hidden from search engine crawling.

Set a noindex meta tag on these pages.

<img width="683" alt="screen shot 2019-01-14 at 5 06 18 pm" src="https://user-images.githubusercontent.com/3453188/51144452-18c30e80-181f-11e9-92e0-e397539bb38c.png">

**Comment by WillCPP** [comment]
Fixed in 6cb74aee5ee24ae1a9fedb4747548151a6b9307d
and 5717ef8001d52a42b127a8bcaaee677b72a79f7e
