### ISSUE TITLE
404 page needs work

### ISSUE THREAD

**Issue by domfarolino** [RevolutionUC/revolutionuc-frontend#82]
Anyone else seeing this?

<img width="704" alt="screen shot 2019-01-19 at 3 21 55 pm" src="https://user-images.githubusercontent.com/9669289/51431970-74661100-1bfe-11e9-8f8a-c29cce2872d6.png">

**Comment by WillCPP** [comment]
Fixed in 1f9867abf4ce80463a74ed5563905ada981cd85a
