### ISSUE TITLE
Sponsors: Partners and Hosted by

### ISSUE THREAD

**Issue by noahbass** [RevolutionUC/revolutionuc-frontend#83]
On the sponsors page:

Add a 'Partners' heading with these partners underneath:
 - Cyber@UC
 - MLH

Add a 'Hosted By' or 'Organized By' heading with ACM@UC underneath

**Comment by WillCPP** [comment]
Fixed in 4e1d3ee2a7ddfbb7faf62dbb6ea8e035a7b8b82c
