### ISSUE TITLE
Update the registration page to include an e-sign waiver

### ISSUE THREAD

**Issue by WillCPP** [RevolutionUC/revolutionuc-frontend#95]
- [x] Opens up a modal popup before when the register button is clicked
- [x] Provide the complete text of the waiver in the popup
- [x] Provide a link to the waiver for reference after a user registers (link to revolutionuc.com/waiver)
- [x] Provide an intent to sign (Accept Waiver button in modal window with text "Accept Waiver and Finish Registration")
- [x] Include an esignedWaiver variable in the data sent to the backend
- [x] Check if age of participant is < 18 (guardian needed for signing, display text saying they will receive more info in an email closer to the event)

**Comment by devagrawal09** [comment]
> Include an esignedWaiver variable in the data sent to the backend

Is this really needed since using the normal flow of the app it's impossible to register without completing the esignwaiver

**Comment by WillCPP** [comment]
Yes, this is needed.  To be in compliance of the ESIGN legislation, we need to keep an electronic record in our database of their signing.  We also need it so that we can verify that an individual registered without finding a way to avoid the e-signature step.
